/*
 *******************************************************************************
 * Copyright (c) 2020, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_WL31K8VX) || defined(ARDUINO_GENERIC_WL31KBVX) ||\
    defined(ARDUINO_GENERIC_WL33K8VX) || defined(ARDUINO_GENERIC_WL33K8VXX) ||\
    defined(ARDUINO_GENERIC_WL33KBVX) || defined(ARDUINO_GENERIC_WL33KBVXX) ||\
    defined(ARDUINO_GENERIC_WL33KCVX) || defined(ARDUINO_GENERIC_WL33KCVXX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
