language: python
python:
  - "3.6"
os:
  - linux
matrix:
  include:
  - env:
      - NAME= arduinoCI
      - IDE_VERSION=1.8.8
    # Use in CI/build/conf/path_config_travis.json
      - ARDUINO_IDE_PATH=$HOME/IDE/arduino
    install:
    # Install Arduino IDE
      - mkdir -p $ARDUINO_IDE_PATH
      - wget http://downloads.arduino.cc/arduino-$IDE_VERSION-linux64.tar.xz
      - tar xf arduino-$IDE_VERSION-linux64.tar.xz --strip-components=1 -C $ARDUINO_IDE_PATH
      - rm arduino-$IDE_VERSION-linux64.tar.xz
    # Install STM32 core supported by ST
      - cd $ARDUINO_IDE_PATH
        # Add json packages url to the Arduino IDE
      - ./arduino --save-prefs --pref "boardsmanager.additional.urls=https://github.com/stm32duino/BoardManagerFiles/raw/master/STM32/package_stm_index.json"
        # Install the latest core version
      - ./arduino --install-boards STM32:stm32
      - rm -fr $HOME/.arduino15/packages/STM32/hardware/stm32/*
        # Replace default core with the one being built
      - sudo ln -s $TRAVIS_BUILD_DIR $HOME/.arduino15/packages/STM32/hardware/stm32/*
    before_script:
      - cd $TRAVIS_BUILD_DIR/CI/build/
      - cp ./conf/path_config_travis.json ./path_config.json
    script:
      - python arduino-builder.py --travis
    after_failure:
      - echo " The build is failed. If script return a non-zero return status , we suggest you to take the above logs into consideration. Otherwise, consult the TRAVIS CI documentation to learn more about build failure" 
notifications:
  email:
    on_success: always
    on_failure: always
