# SPDX-License-Identifier: BSD-3-Clause
# Copyright (c) 2020 STMicroelectronics

name: open-amp lib Continuous Integration

on:
  push:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**
  pull_request:
    branches: [ master ]
    paths-ignore:
      - docs/**
      - cmake/**
      - scripts/**

jobs:
  platform_builds:
    name: check builds on different platforms
    runs-on: ubuntu-latest
    steps:
    - name: Checkout open-amp
      uses: actions/checkout@v2
    - name: Checkout libmetal
      uses: actions/checkout@v2
      with:
        repository: OpenAMP/libmetal
        path: libmetal
    - name: build for Linux
      id: build_linux
      uses: ./.github/actions/build_ci
      with:
        target: linux
    - name: build for Zephyr
      id: build_Zephyr
      uses: ./.github/actions/build_ci
      with:
        target: zephyr
    - name: build for generic arm
      id: build_generic
      uses: ./.github/actions/build_ci
      with:
        target: generic
