/*
 *******************************************************************************
 * Copyright (c) 2020, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_G473VBHX) || defined(ARDUINO_GENERIC_G473VBTX) ||\
    defined(ARDUINO_GENERIC_G473VCHX) || defined(ARDUINO_GENERIC_G473VCTX) ||\
    defined(ARDUINO_GENERIC_G473VEHX) || defined(ARDUINO_GENERIC_G473VETX) ||\
    defined(ARDUINO_GENERIC_G474VBHX) || defined(ARDUINO_GENERIC_G474VBTX) ||\
    defined(ARDUINO_GENERIC_G474VCHX) || defined(ARDUINO_GENERIC_G474VCTX) ||\
    defined(ARDUINO_GENERIC_G474VEHX) || defined(ARDUINO_GENERIC_G474VETX) ||\
    defined(ARDUINO_GENERIC_G483VEHX) || defined(ARDUINO_GENERIC_G483VETX) ||\
    defined(ARDUINO_GENERIC_G484VEHX) || defined(ARDUINO_GENERIC_G484VETX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
