/*
 *******************************************************************************
 * Copyright (c) 2020-2021, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_L100C6UX) || defined(ARDUINO_GENERIC_L100C6UXA) ||\
    defined(ARDUINO_GENERIC_L151C6TX) || defined(ARDUINO_GENERIC_L151C6TXA) ||\
    defined(ARDUINO_GENERIC_L151C6UX) || defined(ARDUINO_GENERIC_L151C6UXA) ||\
    defined(ARDUINO_GENERIC_L151C8TX) || defined(ARDUINO_GENERIC_L151C8TXA) ||\
    defined(ARDUINO_GENERIC_L151C8UX) || defined(ARDUINO_GENERIC_L151C8UXA) ||\
    defined(ARDUINO_GENERIC_L151CBTX) || defined(ARDUINO_GENERIC_L151CBTXA) ||\
    defined(ARDUINO_GENERIC_L151CBUX) || defined(ARDUINO_GENERIC_L151CBUXA) ||\
    defined(ARDUINO_GENERIC_L152C6TX) || defined(ARDUINO_GENERIC_L152C6TXA) ||\
    defined(ARDUINO_GENERIC_L152C6UX) || defined(ARDUINO_GENERIC_L152C6UXA) ||\
    defined(ARDUINO_GENERIC_L152C8TX) || defined(ARDUINO_GENERIC_L152C8TXA) ||\
    defined(ARDUINO_GENERIC_L152C8UX) || defined(ARDUINO_GENERIC_L152C8UXA) ||\
    defined(ARDUINO_GENERIC_L152CBTX) || defined(ARDUINO_GENERIC_L152CBTXA) ||\
    defined(ARDUINO_GENERIC_L152CBUX) || defined(ARDUINO_GENERIC_L152CBUXA)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
