/*
 *******************************************************************************
 * Copyright (c) 2020-2021, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_L072CBTX) || defined(ARDUINO_GENERIC_L072CBUX) ||\
    defined(ARDUINO_GENERIC_L072CZTX) || defined(ARDUINO_GENERIC_L072CZUX) ||\
    defined(ARDUINO_GENERIC_L073CBTX) || defined(ARDUINO_GENERIC_L073CBUX) ||\
    defined(ARDUINO_GENERIC_L073CZTX) || defined(ARDUINO_GENERIC_L073CZUX) ||\
    defined(ARDUINO_GENERIC_L082CZUX) || defined(ARDUINO_GENERIC_L083CBTX) ||\
    defined(ARDUINO_GENERIC_L083CZTX) || defined(ARDUINO_GENERIC_L083CZUX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
