/*
 *******************************************************************************
 * Copyright (c) 2020-2021, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_F427IGHX) || defined(ARDUINO_GENERIC_F427IGTX) ||\
    defined(ARDUINO_GENERIC_F427IIHX) || defined(ARDUINO_GENERIC_F427IITX) ||\
    defined(ARDUINO_GENERIC_F429IEHX) || defined(ARDUINO_GENERIC_F429IETX) ||\
    defined(ARDUINO_GENERIC_F429IGHX) || defined(ARDUINO_GENERIC_F429IGTX) ||\
    defined(ARDUINO_GENERIC_F429IIHX) || defined(ARDUINO_GENERIC_F429IITX) ||\
    defined(ARDUINO_GENERIC_F437IGHX) || defined(ARDUINO_GENERIC_F437IGTX) ||\
    defined(ARDUINO_GENERIC_F437IIHX) || defined(ARDUINO_GENERIC_F437IITX) ||\
    defined(ARDUINO_GENERIC_F439IGHX) || defined(ARDUINO_GENERIC_F439IGTX) ||\
    defined(ARDUINO_GENERIC_F439IIHX) || defined(ARDUINO_GENERIC_F439IITX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
