/*
 *******************************************************************************
 * Copyright (c) 2020-2021, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_L151V8HX) || defined(ARDUINO_GENERIC_L151V8HXA) ||\
    defined(ARDUINO_GENERIC_L151V8TX) || defined(ARDUINO_GENERIC_L151V8TXA) ||\
    defined(ARDUINO_GENERIC_L151VBHX) || defined(ARDUINO_GENERIC_L151VBHXA) ||\
    defined(ARDUINO_GENERIC_L151VBTX) || defined(ARDUINO_GENERIC_L151VBTXA) ||\
    defined(ARDUINO_GENERIC_L152V8HX) || defined(ARDUINO_GENERIC_L152V8HXA) ||\
    defined(ARDUINO_GENERIC_L152V8TX) || defined(ARDUINO_GENERIC_L152V8TXA) ||\
    defined(ARDUINO_GENERIC_L152VBHX) || defined(ARDUINO_GENERIC_L152VBHXA) ||\
    defined(ARDUINO_GENERIC_L152VBTX) || defined(ARDUINO_GENERIC_L152VBTXA)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
