/*
 *******************************************************************************
 * Copyright (c) 2020, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_MP133AAEX) || defined(ARDUINO_GENERIC_MP133AAFX) ||\
    defined(ARDUINO_GENERIC_MP133AAGX) || defined(ARDUINO_GENERIC_MP133CAEX) ||\
    defined(ARDUINO_GENERIC_MP133CAFX) || defined(ARDUINO_GENERIC_MP133CAGX) ||\
    defined(ARDUINO_GENERIC_MP133DAEX) || defined(ARDUINO_GENERIC_MP133DAFX) ||\
    defined(ARDUINO_GENERIC_MP133DAGX) || defined(ARDUINO_GENERIC_MP133FAEX) ||\
    defined(ARDUINO_GENERIC_MP133FAFX) || defined(ARDUINO_GENERIC_MP133FAGX) ||\
    defined(ARDUINO_GENERIC_MP135AAEX) || defined(ARDUINO_GENERIC_MP135AAFX) ||\
    defined(ARDUINO_GENERIC_MP135AAGX) || defined(ARDUINO_GENERIC_MP135CAEX) ||\
    defined(ARDUINO_GENERIC_MP135CAFX) || defined(ARDUINO_GENERIC_MP135CAGX) ||\
    defined(ARDUINO_GENERIC_MP135DAEX) || defined(ARDUINO_GENERIC_MP135DAFX) ||\
    defined(ARDUINO_GENERIC_MP135DAGX) || defined(ARDUINO_GENERIC_MP135FAEX) ||\
    defined(ARDUINO_GENERIC_MP135FAFX) || defined(ARDUINO_GENERIC_MP135FAGX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
