name=I3C
version=0.1.0
author=Bahssain Aymane
maintainer=stm32duino
sentence=Arduino-friendly I3C for STM32 mcu with I3C support.
paragraph=Provides a lightweight I3C bus class (I3CBus).
category=Communication
url=https://github.com/STMicroelectronics/STM32I3C
architectures=stm32
