#ifndef __ES_SENSORS_ADDRESS__
#define __ES_SENSORS_ADDRESS__

#include "project_configuration.h"

#ifndef SENSORS_BME280_ADDRESS
#define SENSORS_BME280_ADDRESS 0x76
#endif /* SENSORS_BME280_ADDRESS */

#ifndef SENSORS_BME68X_ADDRESS
#define SENSORS_BME68X_ADDRESS 0x77
#endif /* SENSORS_BME68X_ADDRESS */

#ifndef SENSORS_KX023_ADDRESS
#define SENSORS_KX023_ADDRESS 0x1F
#endif /* SENSORS_KX023_ADDRESS */

#ifndef SENSORS_LIS3DHTR_ADDRESS
#define SENSORS_LIS3DHTR_ADDRESS 0x19
#endif /* SENSORS_LIS3DHTR_ADDRESS */

#endif /* __ES_SENSORS_ADDRESS__ */
