#ifndef PROJECT_CONFIGURATION_H
#define PROJECT_CONFIGURATION_H

#define LORA_SENDING_PERIOD_S (15*60)

#define GNSS_WAITING_TIME_S (30)
#define GNSS_MIN_READING_TIME_S (3*60)

#define ADC_AREF 3.3f
#define BATVOLT_R1 1.0f
#define BATVOLT_R2 1.0f

#endif /* PROJECT_CONFIGURATION_H */
