name: PlatformIO build
on:
  push:
    branches:
      - main
    paths-ignore:
      - .github/**
      - '!.github/actions/pio-build/**'
      - '!.github/workflows/PIO-build.yml'
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/platformio-builder.py'
      - cmake/**
      - tools/**
      - '!tools/platformio-build.py'
  pull_request:
    paths-ignore:
      - .github/**
      - '!.github/actions/pio-build/**'
      - '!.github/workflows/PIO-build.yml'
      - '*.json'
      - '**.md'
      - keywords.txt
      - CI/**
      - '!CI/build/platformio-builder.py'
      - cmake/**
      - tools/**
      - '!tools/platformio-build.py'
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  pio_build:
    runs-on: ubuntu-latest
    name: PlatformIO test
    steps:
      # First of all, clone the repo using the checkout action.
    - name: Checkout
      uses: actions/checkout@main

    # - name: PlatformIO
    #   id: Compile
    #   uses: ./.github/actions/pio-build
    # Use the output from the `Astyle` step
    - name: Warning
      run: |
        echo "PlatformIO build disabled while not support CMSIS update."
        exit 0
