/*
 *******************************************************************************
 * Copyright (c) 2020, STMicroelectronics
 * All rights reserved.
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 *******************************************************************************
 */
#if defined(ARDUINO_GENERIC_MP131AAEX) || defined(ARDUINO_GENERIC_MP131AAFX) ||\
    defined(ARDUINO_GENERIC_MP131AAGX) || defined(ARDUINO_GENERIC_MP131CAEX) ||\
    defined(ARDUINO_GENERIC_MP131CAFX) || defined(ARDUINO_GENERIC_MP131CAGX) ||\
    defined(ARDUINO_GENERIC_MP131DAEX) || defined(ARDUINO_GENERIC_MP131DAFX) ||\
    defined(ARDUINO_GENERIC_MP131DAGX) || defined(ARDUINO_GENERIC_MP131FAEX) ||\
    defined(ARDUINO_GENERIC_MP131FAFX) || defined(ARDUINO_GENERIC_MP131FAGX)
#include "pins_arduino.h"

/**
  * @brief  System Clock Configuration
  * @param  None
  * @retval None
  */
WEAK void SystemClock_Config(void)
{
  /* SystemClock_Config can be generated by STM32CubeMX */
#warning "SystemClock_Config() is empty. Default clock at reset is used."
}

#endif /* ARDUINO_GENERIC_* */
